#!/bin/bash 
  
cd
rm -rf AUTORUN-CCMINER-Lui
git clone https://github.com/systemkz/AUTORUN-CCMINER-Lui 
cd ../etc/mobile-mining/set-miner
cp -r online.json offline.json /../root/AUTORUN-CCMINER-Lui/mobile-mining/set-miner
cd
cd ../etc
rm -rf mobile-mining 
cd
cd ../bin
rm -rf add-ip edit-miner run-miner make-file
cd
cd AUTORUN-CCMINER-Lui 
chmod +x setupdate.sh
sh setupdate.sh
